app-config:
  llm: 'mistralai/Mixtral-8x7B-Instruct-v0.1'
  huggingface-hub-token: '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'
  prompt_template: 'prompts/prompt.txt'
  log_prompts: false
  log_llm_responses: false
  show_sentence: false
  show_responses_analisys: true